import type { LeagueKey } from './sports-directory';

const ESPN: Record<LeagueKey,{sport:string;slug:string;label:string}> = {
  mlb:{sport:'baseball',slug:'mlb',label:'MLB'}, nfl:{sport:'football',slug:'nfl',label:'NFL'}, nba:{sport:'basketball',slug:'nba',label:'NBA'},
  ncaaf:{sport:'football',slug:'college-football',label:'NCAAF'}, ncaab:{sport:'basketball',slug:'mens-college-basketball',label:'NCAAB'},
};

type WindowKey='10'|'30'|'season';
type Metric={label:string;rate:number|null;wins:number;losses:number;pushes:number;sample:number};
type TrendGame={date:string;opponent:string;location:'home'|'away';teamScore:number;opponentScore:number;spread:number|null;coverResult:'W'|'L'|'P'|null;moneyline:number|null;total:number|null;totalResult:'O'|'U'|'P'|null;source:string|null};
export type BettingTrendsResponse={league:string;leagueLabel:string;team:string;teamName:string;window:string;windowLabel:string;gamesReviewed:number;gamesWithOdds:number;providerSummary?:string;metrics:Record<string,Metric>;recent:TrendGame[];warning?:string|null};
function obj(v:any){return v&&typeof v==='object'?v:{}}
function n(v:any):number|null{if(typeof v==='number'&&Number.isFinite(v))return v;if(typeof v==='string'&&v.trim()){const x=Number(v);return Number.isFinite(x)?x:null}return null}
function price(v:any):number|null{if(typeof v==='number'&&Number.isFinite(v))return v;if(typeof v==='string'){const m=v.match(/[+-]?\d+/);return m?Number(m[0]):null}return null}
async function json(r:Response){const text=await r.text();if(!text.trim())throw new Error(`Empty response (${r.status||'network'})`);let p:any;try{p=JSON.parse(text)}catch{throw new Error(`Invalid JSON (${r.status||'network'})`)}if(!r.ok)throw new Error(p?.detail||p?.error||`Request failed (${r.status})`);return p}
function final(e:any){const t=obj(obj(e?.status).type);return t.completed===true||String(t.state??t.name??'').toLowerCase()==='post'||String(t.name??'').toLowerCase().includes('final')}
function compactDate(d:Date){return `${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`}
function dateAgo(days:number){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-days);return d}
function parseMarket(raw:any){const pc=obj(raw);if(!Object.keys(pc).length)return null;const spread=n(pc.spread),away=obj(pc.awayTeamOdds),home=obj(pc.homeTeamOdds),awayFav=away.favorite===true,homeFav=home.favorite===true;return{awaySpread:spread===null?null:awayFav?-Math.abs(spread):homeFav?Math.abs(spread):null,homeSpread:spread===null?null:homeFav?-Math.abs(spread):awayFav?Math.abs(spread):null,awayMoneyline:price(away.moneyLine),homeMoneyline:price(home.moneyLine),total:n(pc.overUnder)}}
function scoreboardMarket(comp:any){const o=obj(comp?.odds?.[0]);if(!Object.keys(o).length)return null;return parseMarket(o)}
async function marketFor(league:LeagueKey,event:any){const cfg=ESPN[league],id=String(event?.id??'');if(id){try{const r=await fetch(`/espn/apis/site/v2/sports/${cfg.sport}/${cfg.slug}/summary?event=${encodeURIComponent(id)}`,{cache:'no-store'});const s=await json(r),pc=Array.isArray(s?.pickcenter)?s.pickcenter[0]:null,m=parseMarket(pc);if(m)return{market:m,source:'ESPN summary/pickcenter'}}catch{/* use scoreboard market */}}const c=obj(event?.competitions?.[0]),m=scoreboardMarket(c);return{market:m,source:m?'ESPN scoreboard odds':null}}
function metric(label:string,rows:Array<'W'|'L'|'P'>):Metric{const wins=rows.filter(x=>x==='W').length,losses=rows.filter(x=>x==='L').length,pushes=rows.filter(x=>x==='P').length,sample=rows.length;return{label,wins,losses,pushes,sample,rate:sample?wins/sample*100:null}}
async function mapLimit<T,R>(items:T[],limit:number,fn:(item:T,index:number)=>Promise<R>){const out=new Array<R>(items.length);let next=0;async function worker(){while(true){const i=next++;if(i>=items.length)return;out[i]=await fn(items[i],i)}}await Promise.all(Array.from({length:Math.min(limit,items.length)},()=>worker()));return out}

async function directTrends(league:LeagueKey,teamAbbr:string,windowKey:WindowKey):Promise<BettingTrendsResponse>{
 const cfg=ESPN[league],target=windowKey==='10'?10:windowKey==='30'?30:60,events:any[]=[];
 for(let off=0;off<(windowKey==='season'?365:500)&&events.length<target;off+=21){const start=compactDate(dateAgo(off+20)),end=compactDate(dateAgo(off)),range=`${start}-${end}`;try{const r=await fetch(`/espn/apis/site/v2/sports/${cfg.sport}/${cfg.slug}/scoreboard?dates=${range}&limit=1000`,{cache:'no-store'}),p=await json(r);for(const e of Array.isArray(p?.events)?p.events:[]){const c=obj(e?.competitions?.[0]),cs=Array.isArray(c.competitors)?c.competitors:[];if(final(e)&&cs.some((x:any)=>String(x?.team?.abbreviation??'').toUpperCase()===teamAbbr.toUpperCase()))events.push(e)}}catch{/* continue across unsupported date ranges */}}
 const selected=events.sort((a,b)=>String(b.date??'').localeCompare(String(a.date??''))).slice(0,target),markets=await mapLimit(selected,4,(e)=>marketFor(league,e)),history:TrendGame[]=[];let teamName=teamAbbr;
 selected.forEach((e,i)=>{const c=obj(e?.competitions?.[0]),cs=Array.isArray(c.competitors)?c.competitors:[],me=cs.find((x:any)=>String(x?.team?.abbreviation??'').toUpperCase()===teamAbbr.toUpperCase()),op=cs.find((x:any)=>x!==me);if(!me||!op)return;teamName=String(me?.team?.displayName??me?.team?.name??teamName);const ts=n(me.score),os=n(op.score);if(ts===null||os===null)return;const loc: 'home'|'away'=me.homeAway==='home'?'home':'away',m=markets[i]?.market??null,spread=m?(loc==='home'?m.homeSpread:m.awaySpread):null,moneyline=m?(loc==='home'?m.homeMoneyline:m.awayMoneyline):null,total=m?.total??null,adjusted=spread===null?null:ts+spread,cover=adjusted===null?null:adjusted>os?'W':adjusted<os?'L':'P',combined=ts+os,totalResult=total===null?null:combined>total?'O':combined<total?'U':'P';history.push({date:String(e.date??'').slice(0,10),opponent:String(op?.team?.abbreviation??op?.team?.shortDisplayName??'OPP'),location:loc,teamScore:ts,opponentScore:os,spread,coverResult:cover,moneyline,total,totalResult,source:markets[i]?.source??null})});
 const withSpread=history.filter(g=>g.coverResult!==null),overall=withSpread.map(g=>g.coverResult!) as Array<'W'|'L'|'P'>,home=withSpread.filter(g=>g.location==='home').map(g=>g.coverResult!) as Array<'W'|'L'|'P'>,away=withSpread.filter(g=>g.location==='away').map(g=>g.coverResult!) as Array<'W'|'L'|'P'>,favorites=withSpread.filter(g=>(g.spread??0)<0).map(g=>g.coverResult!) as Array<'W'|'L'|'P'>,dogs=withSpread.filter(g=>(g.spread??0)>0).map(g=>g.coverResult!) as Array<'W'|'L'|'P'>,favMl=history.filter(g=>g.moneyline!==null&&g.moneyline<0).map(g=>g.teamScore>g.opponentScore?'W' as const:'L' as const),overs=history.filter(g=>g.totalResult!==null).map(g=>g.totalResult==='O'?'W' as const:g.totalResult==='U'?'L' as const:'P' as const),withOdds=history.filter(g=>g.spread!==null||g.moneyline!==null||g.total!==null),sources=[...new Set(withOdds.map(g=>g.source).filter(Boolean))];
 return{league,leagueLabel:cfg.label,team:teamAbbr,teamName,window:windowKey,windowLabel:windowKey==='10'?'Last 10 completed games':windowKey==='30'?'Last 30 completed games':'Season window',gamesReviewed:history.length,gamesWithOdds:withOdds.length,providerSummary:sources.length?sources.join(' → '):'ESPN direct returned no usable archived market',metrics:{overallCover:metric('Overall cover',overall),homeCover:metric('At home',home),awayCover:metric('On road',away),favoriteCover:metric('As favorite',favorites),underdogCover:metric('As underdog',dogs),favoriteMoneylineWin:metric('Favorite ML wins',favMl),overRate:metric('Games over total',overs)},recent:withOdds.slice(0,8),warning:withOdds.length<Math.min(5,history.length)?'StackBlitz fallback: archived lines appear only when ESPN returns a legitimate market. Missing lines are excluded, never counted as losses.':null};
}

export async function fetchBettingTrends(league:LeagueKey,team:string,w:WindowKey):Promise<BettingTrendsResponse>{
 try{const r=await fetch(`/api/sports/betting-trends?league=${league}&team=${encodeURIComponent(team)}&window=${w}`,{cache:'no-store'});return await json(r) as BettingTrendsResponse}catch{return directTrends(league,team,w)}
}
